import{a as b,S as w,i as a}from"./assets/vendor-BK_rxH-O.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))d(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const l of o.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&d(l)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function d(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();const v="51941180-25d97e4841ef256248244227c",S="https://pixabay.com/api/";async function u(r,t=1){return(await b.get(S,{params:{key:v,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15}})).data}const f=document.querySelector(".gallery"),p=document.querySelector(".load-more"),h=document.querySelector(".loader");let c;function m(r){const t=r.map(s=>`
      <a class="gallery-item" href="${s.largeImageURL}">
        <img src="${s.webformatURL}" alt="${s.tags}" loading="lazy" />
        <div class="info">
          <p><b>Likes:</b> ${s.likes}</p>
          <p><b>Views:</b> ${s.views}</p>
          <p><b>Comments:</b> ${s.comments}</p>
          <p><b>Downloads:</b> ${s.downloads}</p>
        </div>
      </a>`).join("");f.insertAdjacentHTML("beforeend",t),c?c.refresh():c=new w(".gallery a",{captionsData:"alt",captionDelay:250})}function q(){f.innerHTML=""}function y(){h.classList.remove("hidden")}function g(){h.classList.add("hidden")}function E(){p.classList.remove("hidden")}function L(){p.classList.add("hidden")}const R=document.querySelector(".search-form"),P=document.querySelector(".gallery"),$=document.querySelector(".load-more");let i="",n=1;R.addEventListener("submit",async r=>{if(r.preventDefault(),i=r.target.elements.searchQuery.value.trim(),!i){a.error({title:"Error",message:"Please enter a search query!",position:"topRight"});return}n=1,q(),L(),y();try{const t=await u(i,n);if(t.hits.length===0){a.warning({title:"No Results",message:"Sorry, no images found. Please try another search.",position:"topRight"});return}m(t.hits),t.totalHits>n*15&&E()}catch{a.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})}finally{g()}});$.addEventListener("click",async()=>{n+=1,y();try{const r=await u(i,n);m(r.hits),n*15>=r.totalHits&&(L(),a.info({title:"End",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}));const{height:t}=P.firstElementChild.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}catch{a.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})}finally{g()}});
//# sourceMappingURL=index.js.map
