import{a as v,S,i as n}from"./assets/vendor-BK_rxH-O.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const l of o.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&c(l)}).observe(document,{childList:!0,subtree:!0});function a(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function c(e){if(e.ep)return;e.ep=!0;const o=a(e);fetch(e.href,o)}})();const b="51941180-25d97e4841ef256248244227c",q="https://pixabay.com/api/";async function d(r,t=1){return(await v.get(q,{params:{key:b,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15}})).data}const u=document.querySelector(".load-more"),f=document.querySelector(".loader"),p=document.querySelector(".gallery");let E=new S(".gallery a",{captionsData:"alt",captionDelay:250});function h(r){const t=r.map(a=>`
      <li class="gallery-item">
        <a href="${a.largeImageURL}">
          <img src="${a.webformatURL}" alt="${a.tags}" loading="lazy" />
        </a>
        <div class="info">
          <span>Likes: ${a.likes}</span>
          <span>Views: ${a.views}</span>
          <span>Comments: ${a.comments}</span>
          <span>Downloads: ${a.downloads}</span>
        </div>
      </li>`).join("");p.insertAdjacentHTML("beforeend",t),E.refresh()}function P(){p.innerHTML=""}function m(){f.classList.remove("hidden")}function y(){f.classList.add("hidden")}function g(){u.classList.remove("hidden")}function L(){u.classList.add("hidden")}const R=document.querySelector(".search-form"),$=document.querySelector(".gallery"),M=document.querySelector(".load-more");let i="",s=1;const w=15;R.addEventListener("submit",async r=>{if(r.preventDefault(),i=r.target.elements.searchQuery.value.trim(),!i){n.error({title:"Error",message:"Please enter a search query!",position:"topRight"});return}s=1,P(),L(),m();try{const t=await d(i,s);if(t.hits.length===0){n.warning({title:"No Results",message:"Sorry, no images found. Please try another search.",position:"topRight"});return}h(t.hits),t.totalHits>s*w&&g()}catch{n.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})}finally{y()}});M.addEventListener("click",async()=>{L(),s+=1,m();try{const r=await d(i,s);h(r.hits),s*w<r.totalHits?g():n.info({title:"End",message:"We're sorry, but you've reached the end of search results.",position:"topRight"});const{height:t}=$.firstElementChild.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}catch{n.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})}finally{y()}});
//# sourceMappingURL=index.js.map
